### ISSUE TITLE
What's the data structure of the LEVIR-CD? 

### ISSUE THREAD

**Issue by feiqiu-cyber** [wgcban/ChangeFormer#10]
Hello! My LEVIR-CD structure is {train,test,val,list},then {A,B,label,list} under {train,test,val}.When i train,it often has a error like"FileNotFoundError: [Errno 2] No such file or directory: 'CDData/LEVIR-CD256-2/A/train_422_8.png'"

**Comment by wgcban** [comment]
HI @feiqiu-cyber 

I have uploaded my processed LEVIR-CD and DSIFN-CD datasets to the DropBox and you can download the final datasets here:

LEVIR-CD-256: [click here to download](https://www.dropbox.com/sh/lnjxpflvgjijwoj/AAAgWr3xgOjqtTWPVpbLVcfNa?dl=0)
DSIFN-CD-256: [click here to download](https://www.dropbox.com/sh/i54h8kkpgar1s07/AACK5_jLGS3cP9ocgOMEUJcNa?dl=0)
Accordingly, I have updated the readme file as follows:
https://github.com/wgcban/ChangeFormer/blob/main/README.md#links-to-download-processed-datsets-used-for-trainvaltest

It is still uploading and will be available to download after a couple of hours.

I also recommend you to see this issue: https://github.com/wgcban/ChangeFormer/issues/12

Let me know if you have more questions!

Best,
Chaminda
