### ISSUE TITLE
Is it possible to detect multiple classes?

### ISSUE THREAD

**Issue by chartgod** [wgcban/ChangeFormer#102]
Is it possible to detect multiple classes?

**Comment by wgcban** [comment]
yes, check previous issues and discussions

**Comment by chartgod** [comment]
Is it possible to change the detection of the water body? Does the performance in the paper include the change in the detection of the water body?

**Comment by wgcban** [comment]
@chartgod if you wish to detect changes of the water body, you might need to re-train the model (at least fine tune). Because, the current model is trained mainly for building change detection -- which is quite far from water body detection.

**Comment by chartgod** [comment]
thx :D~
