### ISSUE TITLE
Both processed dataset links go to the DropBox of LEVIR-CD256.

### ISSUE THREAD

**Issue by sahin01** [wgcban/ChangeFormer#104]
Can you fix the link for the DSIFN-CD256? Thanks!

**Comment by derow0208** [comment]
try [this](https://www.dropbox.com/s/1lr4m70x8jdkdr0/DSIFN-CD-256.zip?dl=0)

**Comment by wgcban** [comment]
@sahin01 

thanks for the link @derowtosky!
