### ISSUE TITLE
error link for dataset

### ISSUE THREAD

**Issue by sundongwei** [wgcban/ChangeFormer#105]
the link of downloading DSIFN-CD dataset run following command in linux-terminal is not correctly.

**Comment by wgcban** [comment]
@sundongwei Please check again, the link is still active.

**Comment by sundongwei** [comment]
@wgcban  I mean that the different datasets have the same link. 
![Screenshot from 2024-06-03 10-34-56](https://github.com/wgcban/ChangeFormer/assets/30918654/410eca7e-a843-4cdb-bfa3-6f57a19cbae3)

**Comment by Ujjwal238** [comment]
isnt the link that you have provided same?
