### ISSUE TITLE
Hi, are you interested in participating in the Open-CD TRP program?

### ISSUE THREAD

**Issue by likyoo** [wgcban/ChangeFormer#107]
https://github.com/likyoo/open-cd/tree/main/projects/open-cd_technical_report

**Comment by wgcban** [comment]
@likyoo happy to participate! What info do you need?

**Comment by likyoo** [comment]
Nice to hear from you, since ChangeFormer is already supported in open-cd, you only need to provide a description of ChangeFormer. You can send it to me via email (likyoo@sdust.edu.cn). Thank you!!!

**Comment by likyoo** [comment]
@wgcban Hi, Chaminda, I sent you an invitation email and look forward to your reply!

**Comment by likyoo** [comment]
@wgcban Hi, wgcban, how's it going? We plan to release the first version of the technical report on arXiv in the near future, and we would very much appreciate it if you could provide a short description of ChangeFormer. If you don't have time for this, please let us know by 20 July, thank you!
