### ISSUE TITLE
Could you provide the number of params. (M) compared with BiT? 

### ISSUE THREAD

**Issue by shinianzhihou** [wgcban/ChangeFormer#13]
Great Job and could you provide the number of params. (M) compared with BiT?

**Comment by wgcban** [comment]
Hi @shinianzhihou 

Our model has approximately **0.492M** parameters, while BIT-S3 has 1.45M  parameters and BIT-S4 has 3.55M parameters. 

Best,
Chaminda.

**Comment by shinianzhihou** [comment]
emmmm, amazing from 0.492M to 41M.
![image](https://user-images.githubusercontent.com/29772895/178732496-eaf6d504-fdb3-47f3-8dad-c19c99ad9f74.png)

**Comment by Herxinsasa** [comment]
my experiment result shows the number of params is  around 41M not 0.492M

**Comment by wgcban** [comment]
@Herxinsasa You are correct. As I replied [here](https://github.com/wgcban/ChangeFormer/issues/13#issuecomment-1075910205) the number of parameters is close to 41M. The 0.492M was a mistake/miscalculation.

**Comment by zaidbhat1234** [comment]
@wgcban When I try to get the number of parameters, I get this: 67,308,786. I am using torchsummary to get the number of parameters. What could be the reason? I did not change anything in the code and am using the same LEVIR shell script to launch training.
Thanks!

**Comment by yuwanting828** [comment]
Hi@wgcban@zaidbhat1234 Could you provide the number of FLOPs(G) compared with BiT？Thank you very much!

**Comment by Herxinsasa** [comment]
> 
![4DGJPEWGJTQJELD(`V~IR4D](https://user-images.githubusercontent.com/65589596/228137591-4888c203-456e-41b7-adcd-2f27d1b6d75f.png)

**Comment by Herxinsasa** [comment]
> > 
> 
> ![4DGJPEWGJTQJELD(`V~IR4D](https://user-images.githubusercontent.com/65589596/228137591-4888c203-456e-41b7-adcd-2f27d1b6d75f.png)

params/flops
