### ISSUE TITLE
About pre-trained model of  (ADE 160k dataset)

### ISSUE THREAD

**Issue by Youskrpig** [wgcban/ChangeFormer#14]
Hi，I can't enter the download website(DropBox) of model pretrained on ADE dataset.
Would you please provide an access of Github?

**Comment by wgcban** [comment]
Hi @Youskrpig 

I have uploaded it to OneDrive and can you try to download it [here](https://onedrive.live.com/?authkey=%21AJ1viO7flgGisRg&id=B238B6B5231FCF22%216561&cid=B238B6B5231FCF22).

Best,
Chaminda
