### ISSUE TITLE
About other models

### ISSUE THREAD

**Issue by Snail20000624** [wgcban/ChangeFormer#15]
Hi,wgcban!Your project is nice,and I want to use your project in my paper.
But there is some troubles in my process,Can you share the  pretrained models about "CD_SiamUnet_diff" 、"SiamUnet_conc" and so on.
Thank you!

**Comment by wgcban** [comment]
Hi @Snail20000624 

Thank you for your interest in our work. I have uploaded all the pre-trained models for SOTA methods that we used to compare in the paper to DropBox and you can download them through the following link: [Click Here](https://www.dropbox.com/sh/1w265yymqvztkqf/AACqsmND_avIWihjr3GkrSW9a?dl=0).

Also, you can also train these SOTA methods by simply executing the scripts in ``http://changeformer/scripts/run_SOTA/``: [Click Here](http://changeformer/scripts/run_SOTA/). That wont take so long time to train.

I hope this answers your question.

Best,
Chaminda.

**Comment by Snail20000624** [comment]
Good job,wgcban!Thank you!
