### ISSUE TITLE
I found that you may used test-split-data for validation and test in the same time.

### ISSUE THREAD

**Issue by Rit-Shi** [wgcban/ChangeFormer#19]
It seems to be something wrong. And the split of DSIFN Dataset is really weird，
the test set is too small.

**Comment by wgcban** [comment]
Hi @Rit-Shi 
Hey, thanks for pointing out this mistake. I will correct this. The test and val splits of the DSIFN dataset should be interchanged. Instead, you may use val split as the test set when training. 

Best,
Chaminda

**Comment by Rit-Shi** [comment]
OK, I see. Thank you for your reply！
