### ISSUE TITLE
The difference between base_transformer_pos_s4_dd8 and ChangeFormer

### ISSUE THREAD

**Issue by L-xiaolu** [wgcban/ChangeFormer#20]
Sorry to bother you again, I noticed that your model has base_transformer_pos_s4_dd8 in addition to the ChangeFormer schema, I look at the structure of that model. As per your comment, base_transformer_pos_s4_dd8 seems to be a combination of Resnet+BIT+feature diffence+a small CNN. I wonder if it differs from BIT only in these components?

**Comment by wgcban** [comment]
Hi @L-xiaolu 
No problem. Thanks for asking this question.!

You are correct that ``base_transformer_pos_s4_dd8`` uses ResNet encoder to extract features, and then BIT transformer at the bottleneck, then feature difference to detect changes at the feature level, and finally small conv head to get the changes at original HxW scale. This is exactly the implementation of BIT architecture proposed in the original BIT paper  (https://arxiv.org/abs/2103.00208), and if you run this model you should be able to reproduce the results reported in the BIT paper.

In addition, our repository contains several other SOTA methods, namely, **DTCDSCN** (https://arxiv.org/abs/1909.07726), **SiamUnetConc** (https://arxiv.org/abs/1810.08462), **SiamUnetDiff** (https://arxiv.org/abs/1810.08462), and **Unet**. The corresponding script files to evaluate these models can be found in  [ChangeFormer/run_SOTA/](https://github.com/wgcban/ChangeFormer/tree/main/scripts/run_SOTA).

Hope I answered your question.
Best,
Chaminda.

**Comment by L-xiaolu** [comment]
> 你好@L-xiaolu 没问题。感谢您提出这个问题。！
> 
> 您是正确的，`base_transformer_pos_s4_dd8`使用**ResNet**编码器提取特征，然后在瓶颈处使用**BIT转换器，然后****使用特征差异**检测特征级别的变化，最后使用**小 conv head**来获得原始 HxW 尺度的变化。这_正是原始 BIT 论文 ( _https://arxiv.org/abs/2103.00208 )中提出的 BIT 架构的实现，如果您运行此模型，您应该能够重现 BIT 论文中报告的结果。
> 
> 与**BIT** (base_transformer_pos_s4_dd8) 不同，**ChangeFormer**使用 Complete Transformer Encoder（即非局部注意力网络）作为编码器，使用 MLP head 作为解码器。因此，在我们的 ChangeFormer 论文中，我们证明了对**ConvNets**的依赖是**不必要**的，具有**轻量级 MLP解码器的****分层变换器编码**器可以很好地用于 CD 任务。****
> 
> 这里我引用了我们的 ChangeFormer 论文的最后一段，它解释了 ChangeFormer 与 BIT 的不同之处：
> 
> > 尽管 Transformer 网络具有更大的感受野和更强的上下文塑造能力，但针对 CD 的 Transformer 的工作却很少。在最近的一项工作 [4] (BIT) 中，变压器架构与 ConvNet 编码器 (ResNet18) 结合使用，以增强特征表示，同时保持整体基于 ConvNet 的特征提取过程到位。在本文中，我们表明这种对 ConvNets 的依赖是不必要的，具有轻量级 MLP 解码器的分层变换器编码器可以很好地用于 CD 任务。
> 
> 此外，我们的存储库还包含其他几种 SOTA 方法，即DTCDSCN **(** https://arxiv.org/abs/1909.07726)、SiamUnetConc [(](https://arxiv.org/abs/1909.07726) https://arxiv.org/abs/1810.08462)、SiamUnetDiff [( ](https://arxiv.org/abs/1810.08462)**https** : [// ](https://arxiv.org/abs/1810.08462)**arxiv **[.org/abs/1810.08462](https://arxiv.org/abs/1810.08462)）和**Unet**。评估这些模型的相应脚本文件可以在 [ChangeFormer/run_SOTA/](https://github.com/wgcban/ChangeFormer/tree/main/scripts/run_SOTA)中找到。[](https://arxiv.org/abs/1810.08462)****[](https://arxiv.org/abs/1810.08462)****[](https://github.com/wgcban/ChangeFormer/tree/main/scripts/run_SOTA)
> 
> 希望我回答了你的问题。 最好的， 查明达。

Thank you for your answer, I understand.

**Comment by zdw9915** [comment]
Sorry to bother you, I would like to ask the difference between the three?
 base_transformer_pos_s4，base_transformer_pos_s4_dd8 and base_transformer_pos_s4_dd8_dedim8） 
If you have time, please take the trouble to answer it. Thank you so much!

**Comment by wulei1595** [comment]
> Sorry to bother you, I would like to ask the difference between the three? base_transformer_pos_s4，base_transformer_pos_s4_dd8 and base_transformer_pos_s4_dd8_dedim8） If you have time, please take the trouble to answer it. Thank you so much!
Do you know the three differences between them?

**Comment by wulei1595** [comment]
> 很抱歉打扰您，我想问一下三者之间的区别？ base_transformer_pos_s4，base_transformer_pos_s4_dd8和base_transformer_pos_s4_dd8_dedim8）如果您有时间，请不厌其烦地回答。非常感谢！

你知道三个的区别吗

**Comment by L-xiaolu** [comment]
原作者也没怎么说明白，我自己也没怎么明白，这三个模型好像就是架构上的区别，也可能是特征维度不一样，我记得当时给我说的好像就是架构上的区别，具体的详细内容，你只能看代码实现了
