### ISSUE TITLE
training results are very different from BIT

### ISSUE THREAD

**Issue by Yanll2021** [wgcban/ChangeFormer#25]

**Comment by Yanll2021** [comment]
Hi, sorry to bother you here. I would like to ask why I use your code and BIT code on the same data set training BIT model, but the result is very different, using your model training results are much higher than the training results in BIT source code？
For example, I train the base_transformer_pos_s4_dd8 model with your code in the same WHU dataset, IOU_1 is 81.664, but train the same model with BIT source code and IOU_1 is 67.164, why is there such a big difference?  Did you use a special technique when you trained the model? 
 the code in your .sh is:
![1653623819(1)](https://user-images.githubusercontent.com/78201260/170626345-36aa9a03-6a7a-44c6-8793-f2a79855a8e3.jpg)

**Comment by Drchip61** [comment]
I train bit code on Google dataset and get a quite low performance as well

**Comment by wgcban** [comment]
@Drchip61 I am quite not sure about why BIT is giving less performance though we use the same implementation.
