### ISSUE TITLE
How to download pretrained weights (segformer.b2.512x512.ade.160k.pth)?

### ISSUE THREAD

**Issue by zccjyo** [wgcban/ChangeFormer#26]
Hello, thank you for your idea. I have a trouble. In the file (run_ChangeFormer_LEVIR.sh), I find that you use pretrained weights of Segformer.b2.512×512.ade.160k.pth, but I only found the weight of version b1 on github of segformer. So can you share the Segformer.b2.512×512.ade.160k.pth for me? Thank you.

**Comment by wgcban** [comment]
Hi @zccjyo 
Please refer to this section: https://github.com/wgcban/ChangeFormer#speech_balloon-train-on-levir-cd

**Comment by zccjyo** [comment]
I get it.Thank you.
