### ISSUE TITLE
FileNotFoundError: no such checkpoint best_ckpt.pt

### ISSUE THREAD

**Issue by souvik0306** [wgcban/ChangeFormer#27]
Hi

I'm trying to implement the Change Former Repo for a Remote Sensing Application involving change detection. 

I have downloaded the required **ChangeFormerV6 pretrained model** from - [GitHub](https://github.com/wgcban/ChangeFormer/releases/download/v0.1.0/CD_ChangeFormerV6_LEVIR_b16_lr0.0001_adamw_train_test_200_linear_ce_multi_train_True_multi_infer_False_shuffle_AB_False_embed_dim_256.zip) as specified.

The [README.d](https://github.com/wgcban/ChangeFormer#speech_balloon-quick-start-on-levir-dataset) of the repository states that only a folder `checkpoints/ChangeFormer_LEVIR` is to be added as per user in order to run demo_LEVIR.py.

Here are the `best_ckpt.pt` file paths as per my system - 

    checkpoint_root = r'checkpoints\ChangeFormer_LEVIR\CD_ChangeFormerV6_LEVIR_b16_lr0.0001_adamw_train_test_200_linear_ce_multi_train_True_multi_infer_False_shuffle_AB_False_embed_dim_256\best_ckpt.pt'

### The Folder Structure used -
    .
    ├── ChangeFormer
    │   ├── checkpoints
           ├── ChangeFormer_LEVIR       
              ├── CD_ChangeFormerV6_LEVIR_b16_lr0.0001_adamw_train_test_200_linear_ce_multi_train_True_multi_infer_False_shuffle_AB_False_embed_dim_256   
                 ├── best_ckpt.pt
    │   ├── **demo_LEVIR.py**
    │   ├── data_preparation
    │   ├── utils.py  
    │   ├── datasets
    │   ├── images   
    │   ├── misc
    │   ├── models
    │   ├── samples
                ├── predict_LEVIR        
    │   ├── requirements.txt
    │   ├── samples_LEVIR
    │   ├── scripts        
    │   └── README.md 
     
On executing as specified I encountered the following error- 

     FileNotFoundError: no such checkpoint best_ckpt.pt

Does one need to modify the Dataset structure to run the **_demo_LEVIR.py_** code? Please provide adequate insight on this issue

**Comment by wgcban** [comment]
We find checkpoint_dir as checkpoint_root +  args.project_name here https://github.com/wgcban/ChangeFormer/blob/b0f2d09f2c457a5886f4808ac8239f20bb9db554/demo_LEVIR.py#L56

Then we get the path to saved model as:  checkpoint_dir+best_ckpt.pt here: https://github.com/wgcban/ChangeFormer/blob/b0f2d09f2c457a5886f4808ac8239f20bb9db554/models/basic_model.py#L32
