### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by choumie** [wgcban/ChangeFormer#28]
Hi
I really appreciate your work. I have a few questions about the model. First of all is it possible to modify the size of the input images?
Then how can we retrain the model with our data?
I noticed that the model detects the changes appeared in the image B. How can we generate a map for the disappearance of elements in A?
Thanks. I remain open to your answers and suggestions.

**Comment by wgcban** [comment]
Hi @choumie 
Thank you for your interest. The model is able to take care of the different sizes of the images during the testing due to convolutional positional embedding. Sorry, I dint understand your 2nd and 3rd questions well. Can you elaborate more on it?
Thanks.

**Comment by choumie** [comment]
How can I change the size please? 
I would like to know how can I use the best checkpoint to train with my data?
And when I try the model, I remark that it's just the objects that appeared in B that are detected in the generate mask. So How can I use your code to generate a map for the objects that have disappeared on A

**Comment by wgcban** [comment]
- Regarding the size: you can set the --image_size parameter here: https://github.com/wgcban/ChangeFormer/blob/193743a351f7cc7b4674e896bd1387874bf4667d/eval_cd.py#L31 during the **validation**.
- Regarding your second question: We train the network to detect changes, and we do not impose any additional constraints on the changes. So the network is able to detect any changes in images A and B. If you have an object that disappeared in image A, the network will detect it. There is no order in images A or B. You should be able to get the same change detection map even if you change the order of image A and image B. 

I hope this will answer your question. Let me know if you have further questions.

**Comment by choumie** [comment]
Hi @wgcban 
Thank you for your answer.
When I try to reserve A and B for prediction I obtain for example this image
![difference](https://user-images.githubusercontent.com/97854702/181784574-1b9bbec2-1891-4b54-b7f5-1c514630e692.png)

**Comment by wgcban** [comment]
Hi @choumie 
This seems an interesting observation. I didn't think about this before. Possibly due to the domain shifts between pre-change and post-change images, and we didn't train the network in that way. When training the network, I think if we randomly interchange image A and image B as an augmentation technique, this shouldn't happen during the testing.

But, still, you can train the network with your data to detect changes in image A.
