### ISSUE TITLE
F1 values of WHU-CD and DSIFN-CD

### ISSUE THREAD

**Issue by yuwanting828** [wgcban/ChangeFormer#32]
Hello, I am trying to reproduce the BIT-CD model code, and it looks incorrect when using WHU-CD dataset as well as DSIFN-CD dataset, and the result appears too high than your result. But it looks normal when using LEVID-CD dataset. Do I need to change the pre-training?

**Comment by wgcban** [comment]
@yuwanting828 
Did you use the same hyperparameter values given in the paper?

**Comment by yuwanting828** [comment]
Thank you very much for your reply. The hyperparameters I set in the experiment are based on those in the original paper BIT-CD.

**Comment by wgcban** [comment]
@yuwanting828 Interesting. Could be due to different train/val/test splits?

**Comment by yuwanting828** [comment]
Thanks again for your reply, in my experiments I used the dataset links you provided in the Readme file in the ChangeFormer project and in your reply to the issue.
