### ISSUE TITLE
Pretrained_model issue

### ISSUE THREAD

**Issue by flying318** [wgcban/ChangeFormer#33]
Hi，I'm interested in your project but I met an issue. I can't get the full pretrained model parameters through the link you given in Readme. I have tried many times with IDM connecting failed. Moreover, could you provide them in Google.drive or Baidu netdisk?

**Comment by wgcban** [comment]
Hi @flying318 
Did you try to download the pre-trained model weights via `wget` command?
```
wget https://www.dropbox.com/s/undtrlxiz7bkag5/pretrained_changeformer.pt
```
