### ISSUE TITLE
pretrained model of comparison experiments

### ISSUE THREAD

**Issue by Herxinsasa** [wgcban/ChangeFormer#34]
may i have you pretrained model of contrast model like IFNet、STANet...on these dataset，thank you so much！！！

**Comment by Herxinsasa** [comment]
my email is 17816123245@163.com thank u !!!

**Comment by wgcban** [comment]
Hey @Herxinsasa 
Unfortunately, I do not have the pre-trained models for these networks. These networks are lightweight, do not need many GPUs, and are faster in training. So I didn't keep the pre-trained models of those. But I do have the implementation of those methods integrated in my codebase. You just need to run the sh files in``https://github.com/wgcban/ChangeFormer/tree/main/scripts/run_SOTA`` to get the results for a corresponding method.

**Comment by Herxinsasa** [comment]
This is aslo very helpful for me，thank u so much！！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wele Gedara Chaminda ***@***.***&gt;; 
发送时间: 2022年10月1日(星期六) 下午2:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wgcban/ChangeFormer] pretrained model of comparison experiments (Issue #34)





 
Hey @Herxinsasa
 Unfortunately, I do not have the pre-trained models for these networks. These networks are lightweight, do not need many GPUs, and are faster in training. So I didn't keep the pre-trained models of those. But I do have the implementation of those methods integrated in my codebase. You just need to run the sh files inhttps://github.com/wgcban/ChangeFormer/tree/main/scripts/run_SOTA to get the results for a corresponding method.
