### ISSUE TITLE
The code runs too long

### ISSUE THREAD

**Issue by Mengtao-ship** [wgcban/ChangeFormer#36]
Hello, it's a nice code.
It takes me a lot of time to run the program using the LEVIR-CD-256 dataset you have processed. Is this normal?
How long will it take you to train the model？
Looking forward to your early reply!

**Comment by wgcban** [comment]
Hi @Mengtao-ship 

It depends on the batch size you are using. Usually, it converges pretty fast, and you can see the exact time-stamp of the training in the log file provided along with the pre-trained model. 

For example, in a 48GB GPU, with a batch size of 16, it took about 46hours for 200 epochs to train on LEVIR-CD.

However, you can use the pre-trained models provided for LEVIR-CD and DSIFN-CD to get results without training.

**Comment by wgcban** [comment]
You may refer [Quick Start on LEVIR dataset](https://github.com/wgcban/ChangeFormer/issues/13#issuecomment-1075910205) to find the link to pre-trained models on LEVIR-CD dataset.

**Comment by Mengtao-ship** [comment]
I use the dataset you provided on [https://github.com/wgcban/ChangeFormer#point_right-links-to-download-processed-datsets-used-for-trainvaltest].It contains more than 10,000 pairs of pictures in total.Due to the limitation of my GPU, I set the batch size to 14. An epoch takes about 4 hours.Do you use this dataset during training？

**Comment by wgcban** [comment]
@Mengtao-ship Yes, I used the provided dataset during training. Reducing the batch size from 16 to 14 should not give that much time difference for an epoch. As I remember, it was 15-20 mins per epoch. 

Can you also try on other datasets?
