### ISSUE TITLE
pretrained model on WHU dataset

### ISSUE THREAD

**Issue by Herxinsasa** [wgcban/ChangeFormer#37]
Could you share your training results on the WHU dataset as a comparison experiment, please? my email is 1277434449@qq.com!

**Comment by wgcban** [comment]
@Herxinsasa Actually, I do not have the pre-trained model on the WHU-CD dataset. I recommend you train a model on the WHU-CD dataset by initializing the model pre-trained on LEVIR-CD or DSIFN-CD dataset for faster convergence as per the instructions given in the README. However, if you just need the F1 and IOU scores, you can probably find them in the papers which cite ChangeFormer. I have seen some papers compare the results of ChangeFormer on the WHU-CD dataset.

**Comment by Herxinsasa** [comment]
thank u！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wele Gedara Chaminda ***@***.***&gt;; 
发送时间: 2022年10月12日(星期三) 晚上7:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wgcban/ChangeFormer] pretrained model on WHU dataset (Issue #37)





 
@Herxinsasa Actually, I do not have the pre-trained model on the WHU-CD dataset. I recommend you train a model on the WHU-CD dataset by initializing the model pre-trained on LEVIR-CD or DSIFN-CD dataset for faster convergence as per the instructions given in the README. However, if you just need the F1 and IOU scores, you can probably find them in the papers which cite ChangeFormer. I have seen some papers compare the results of ChangeFormer on the WHU-CD dataset.
