### ISSUE TITLE
About the order of Difference Modules and Decoder

### ISSUE THREAD

**Issue by zhao-zh-h** [wgcban/ChangeFormer#39]
According to the network architecture picture, the difference module precedes the decoder, whereas in the corresponding ChangeFormerV6 (the finalized verion), it goes through the decoder before the difference. Is it special handling or a minor error?

**Comment by wgcban** [comment]
@zhao-zh-h This is not an error. 
We found that this slightly improves the results compared to what we originally mentioned in the paper.
Feel free to change the order of these two modules and check the results yourself.

**Comment by zhao-zh-h** [comment]
> @zhao-zh-h This is not an error. We found that this slightly improves the results compared to what we originally mentioned in the paper. Feel free to change the order of these two modules and check the results yourself.

Thank you！
