### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by zyhhh123** [wgcban/ChangeFormer#41]
can't download dataset by using the given command  (wget https://www.dropbox.com/s/h9jl2ygznsaeg5d/LEVIR-CD-256.zip)

--2022-10-30 22:21:34--  (try: 5)  https://www.dropbox.com/s/h9jl2ygznsaeg5d/LEVIR-CD-256.zip
Connecting to www.dropbox.com (www.dropbox.com)|31.13.106.4|:443... failed: Connection timed out.
Connecting to www.dropbox.com (www.dropbox.com)|2001::80f2:f07d|:443... failed: Cannot assign requested address.
Retrying.

--2022-10-30 22:21:17--  (try: 4)  https://www.dropbox.com/sh/i54h8kkpgar1s07/AAA0rBAFl9UZ3U3Z1_o46UT0a/DSIFN-CD-256.zip
Connecting to www.dropbox.com (www.dropbox.com)|108.160.165.48|:443... failed: Connection timed out.
Connecting to www.dropbox.com (www.dropbox.com)|2001::80f2:f07d|:443... failed: Cannot assign requested address.
Retrying.

**Comment by wgcban** [comment]
@zyhhh123 I am not sure why this is happening. I can upload all the datasets to GoogleDrive and share them with you, but I need some time for that.

**Comment by zyhhh123** [comment]
@wgcban Thanks for the replay. I have sucessfully downloaded the dataset from the original links.There is another issue where the changeformer model results on the DSIFN-CD dataset are not consistent with the ddpm-cd results.What changes were made?
