### ISSUE TITLE
about multi classes

### ISSUE THREAD

**Issue by g7199** [wgcban/ChangeFormer#43]
hi, I tried to train my personal data with 4 classes = {0,1,2,3}

pixels are like

0000000002220000
0000000002200000
0000000002000000
0010000000000000
0111110000000000
1111000000000000

grayscale.

when I train this data, the accuracy converges to 0.5 and never changes.
Is there any problem that I miss?

what I changed is only n_classes = 4

thanks.

**Comment by wgcban** [comment]
@g7199 
https://github.com/wgcban/ChangeFormer/issues/42#issuecomment-1304052271

**Comment by g7199** [comment]
I tried it, but same convergence occurs

**Comment by g7199** [comment]
![image](https://user-images.githubusercontent.com/32329162/200614050-136ab61d-b4a9-4588-a403-cc7dec687962.png)

**Comment by g7199** [comment]
solved it but i found another error

![image](https://user-images.githubusercontent.com/32329162/200624749-077fafc5-53af-4569-92f0-ffb11d5dc3c7.png)

is ther anything i missed? ㅜㅜ

**Comment by g7199** [comment]
oh i should not use norm!
I find it
Thanks

**Comment by Programming-Music** [comment]
> > oh i should not use norm! I find it Thanks
> 
> Hello, I have also encountered the same problem as you. Have you resolved it ![image](https://private-user-images.githubusercontent.com/102707449/287743548-1af5afb8-e74f-4247-a834-02871b9b9129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODQ0MTQsIm5iZiI6MTcwNjY4NDExNCwicGF0aCI6Ii8xMDI3MDc0NDkvMjg3NzQzNTQ4LTFhZjVhZmI4LWU3NGYtNDI0Ny1hODM0LTAyODcxYjliOTEyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQwNjU1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjc2NjAyMDE4MDZjN2MzZWYxYTliMzU1ZTZmMTZhYTljZGQ1NDg1OTFmMTc2ZmMxZGEzYTY0MjI1NzRjMGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RYldEsySnUEcqWDxzC4HDjKm7CehD2byLkFq6ZVIK3Y)

Hi, I also had the same problem as you. How did you solve it?
