### ISSUE TITLE
how to detect my dataset?

### ISSUE THREAD

**Issue by stphtan94117** [wgcban/ChangeFormer#44]
i finish LEVIR-CD training and get the new best_ckpt.pt.
So how do i use this new weight(best_ckpt.pt) to predict my picture?

my picture are aerial image (before and after scene, only two images).
before image input A folder
after image input B folder

but i did not label image, so i would not put anything in label folder.
how do i predict my picture?

**Comment by wgcban** [comment]
@stphtan94117 hey,

The label is used to compute the quantitative performance metrics. If you do not have a label available, pls include a dummy label (ie, all zeros) of the same size as input A in the label folder.

Thanks.
