### ISSUE TITLE
How to solve

### ISSUE THREAD

**Issue by ChenTianao** [wgcban/ChangeFormer#45]

**Comment by ChenTianao** [comment]
How to solve this issue?

Hi
The Folder Structure used -
```
 .
├── ChangeFormer
│   ├── checkpoints
       ├── ChangeFormer_LEVIR       
          ├── CD_ChangeFormerV6_LEVIR_b16_lr0.0001_adamw_train_test_200_linear_ce_multi_train_True_multi_infer_False_shuffle_AB_False_embed_dim_256   
             ├── best_ckpt.pt
│   ├── **demo_LEVIR.py**
│   ├── data_preparation
│   ├── utils.py  
│   ├── datasets
│   ├── images   
│   ├── misc
│   ├── models
│   ├── samples
            ├── predict_LEVIR        
│   ├── requirements.txt
│   ├── samples_LEVIR
│   ├── scripts        
│   └── README.md
```

I try to  Quick Start on LEVIR dataset. Also downloaded the required ChangeFormerV6 pretrained model as requested. I also modified my code as shown in the [link](https://github.com/wgcban/ChangeFormer/issues/27). 
![image](https://user-images.githubusercontent.com/81311794/203219415-17ec4523-4bd2-4a5a-8f50-58fe93ffe7e1.png)
But I have encountered a problem that I tried for a long time without being able to solve. 
![image](https://user-images.githubusercontent.com/81311794/203219613-de5fa15d-52e6-4fb5-b95f-d04565f48692.png)
Can you give me some simple instructions so that I can fix it?

**Comment by wgcban** [comment]
@ChenTianao I think in Windows, you should use `\` (instead of `/` in Linux) to specify the path to all models.

**Comment by ChenTianao** [comment]
@wgcban I have changed it. But there are still problems, as shown before. I've tried pip and conda but both have DataLoader error, which direction should I look for to solve the problem?

**Comment by wgcban** [comment]
@ChenTianao, I am glad that you solved the problem. I think this is a problem with your virtual environment. Maybe your virtual environment has not enough memory to support a higher number of workers.
