### ISSUE TITLE
Different number of parameters than reported for ChangeFormer

### ISSUE THREAD

**Issue by zaidbhat1234** [wgcban/ChangeFormer#49]
@wgcban When I try to get the number of parameters, I get this: 67,308,786(~67M). I am using torchsummary to get the number of parameters. What could be the reason? I did not change anything in the code and am using the same LEVIR shell script to launch training. It seems to be different than what you reported (~41M)
Thanks!

**Comment by wgcban** [comment]
Hi @zaidbhat1234 For me it showed ~41M as the number of trainable parameters. I will check it again and confirm with you.

**Comment by zaidbhat1234** [comment]
Hi @wgcban Thanks! Please let me know if it still shows 41M for you and how you measured it.

**Comment by zaidbhat1234** [comment]
@wgcban Nevermind. I figured it was due to some changes I made in the architecture. Have you tried to train a bigger (more parameters) model for ChangeFormer? Could you please highlight the impact of increasing the number of parameters.

**Comment by wgcban** [comment]
@zaidbhat1234 I did not try training bigger models due to the longer pre-training time. But you can always try. Based on my experience, bigger transformer models usually perform better, provided you tune the model correctly. Thanks.
