### ISSUE TITLE
Experiments of ChangeFormer on the CDD dataset and WHU building dataset

### ISSUE THREAD

**Issue by bhpeng21** [wgcban/ChangeFormer#60]
Hello friend, I noticed that in your other project, ddpm-cd, you conducted experiments using changeFormer on the CDD dataset and WHU building dataset. The reported F1-scores were 94.63% and 88.57% respectively. I would like to cite your experimental results in my work, but I also need the corresponding precision and recall metrics. Do you still have access to that data? If so, could you please provide it to me? I would greatly appreciate it.

**Comment by wgcban** [comment]
@bhpeng21 Seems like i did not save the precision and recall values as I can see in the [wandb log file.](https://wandb.ai/wgcban/ddpm-RS-CDHead/reports/Change-Detection-Performance-on-Test-sets-of-LEVIR-CD-WHU-CD-DSIFN-CD-and-CDD--VmlldzoyMDE5NDg5?accessToken=6eikgovmk7ct25ar00eggsuslh8bzdz9e8215qn5xa0omqe5uo5u1jf4lh2liajx). But I have provided the model weights and you can obtain the precision and reall metrics by simply running the test code. Guidelines are given here: https://github.com/wgcban/ddpm-cd#low_brightnesstesting

**Comment by bhpeng21** [comment]
Thank you so much! With your help, my issue has been resolved. Do I need to close this issue myself?

**Comment by wgcban** [comment]
Nice, I am closing the issue.
