### ISSUE TITLE
How to output its prediction plot separately for each test image

### ISSUE THREAD

**Issue by wulei1595** [wgcban/ChangeFormer#62]
How to output its prediction plot separately for each test image

**Comment by itstatev** [comment]
@wulei1595 I am trying to test the project on my own dataset, but I get an error saying " Missing key(s) in state_dict: "pos_embedding", "resnet.conv1.weight", ...". How did you use the weights to make it work?

**Comment by wgcban** [comment]
@itstatev Did you change the model configuration?

**Comment by wgcban** [comment]
@itstatev Using correct config file?
