### ISSUE TITLE
License Term

### ISSUE THREAD

**Issue by zaidbhat1234** [wgcban/ChangeFormer#63]
Could you please let me know the exact licensing term for the codebase? Is it MIT or Apache2.0 License or something else? @wgcban Thanks!

**Comment by wgcban** [comment]
@zaidbhat1234 updated.

**Comment by ggand0** [comment]
@wgcban 
The repo shows MIT (which allows commercial use), but this part of the README says it’s for research/non-commercial use only. Which one is the intended license?

> License
> Code is released for non-commercial and research purposes only. For commercial purposes, please contact the authors.
