### ISSUE TITLE
Missing key(s) in state_dict for BASE_Transformer.

### ISSUE THREAD

**Issue by itstatev** [wgcban/ChangeFormer#64]
I am trying to test ChangeFormer on my own dataset and I get an error saying "I am trying to test the project on my own dataset, but I get an error saying "RuntimeError: Error(s) in loading state_dict for BASE_Transformer: Missing key(s) in state_dict: "pos_embedding", "resnet.conv1.weight", ...". How can I work this out? I downloaded the weights from the Dropbox link mentioned in the repo.

**Comment by wgcban** [comment]
@check if you specify the model name correctly.

**Comment by itstatev** [comment]
@wgcban can you please say where exactly I should check it? I haven't checked anything in the code except the Dataset? I used the best_ckpt.pt for the checkpoints and did not change the model specified in the code.

**Comment by itstatev** [comment]
@wgcban okay, I found it, and changed the model to ChangeFormerV6 as the weights are forChangeFormerV^, but now I get this error 

'RuntimeError: Error(s) in loading state_dict for ChangeFormerV6:
        size mismatch for TDec_x2.linear_c4.proj.weight: copying a param with shape torch.Size([256, 512]) from checkpoint, the shape in current model is torch.Size([64, 512]).
        size mismatch for TDec_x2.linear_c4.proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.linear_c3.proj.weight: copying a param with shape torch.Size([256, 320]) from checkpoint, the shape in current model is torch.Size([64, 320]).
        size mismatch for TDec_x2.linear_c3.proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.linear_c2.proj.weight: copying a param with shape torch.Size([256, 128]) from checkpoint, the shape in current model is torch.Size([64, 128]).
        size mismatch for TDec_x2.linear_c2.proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.linear_c1.proj.weight: copying a param with shape torch.Size([256, 64]) from checkpoint, the shape in current model is torch.Size([64, 64]).
        size mismatch for TDec_x2.linear_c1.proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c4.0.weight: copying a param with shape torch.Size([256, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 128, 3, 3]).
        size mismatch for TDec_x2.diff_c4.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c4.2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c4.2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c4.2.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c4.2.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c4.3.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for TDec_x2.diff_c4.3.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c3.0.weight: copying a param with shape torch.Size([256, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 128, 3, 3]).
        size mismatch for TDec_x2.diff_c3.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c3.2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c3.2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c3.2.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c3.2.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c3.3.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for TDec_x2.diff_c3.3.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c2.0.weight: copying a param with shape torch.Size([256, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 128, 3, 3]).
        size mismatch for TDec_x2.diff_c2.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c2.2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c2.2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c2.2.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c2.2.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c2.3.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for TDec_x2.diff_c2.3.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c1.0.weight: copying a param with shape torch.Size([256, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 128, 3, 3]).
        size mismatch for TDec_x2.diff_c1.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c1.2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c1.2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c1.2.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c1.2.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.diff_c1.3.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for TDec_x2.diff_c1.3.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for TDec_x2.make_pred_c4.0.weight: copying a param with shape torch.Size([2, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([2, 64, 3, 3])....'

'

**Comment by itstatev** [comment]
@wgcban thank you! I changed the model to ChangeFormerV6, because the weights were ChangeFormerV6 weights, but now I want to run main_cd.py and I get this error. By the way I also get it when trying to run demo_LEVIR.py

'Traceback (most recent call last):
  File "demo_LEVIR.py", line 5, in <module>
    from models.basic_model import CDEvaluator
  File "/home/tatev/ChangeFormer/models/basic_model.py", line 3, in <module>
    import cv2
ImportError: libopenh264.so.5: cannot open shared object file: No such file or directory'
