### ISSUE TITLE
why cancel BN and last relu  in ResidualBlock？

### ISSUE THREAD

**Issue by yangjian1218** [wgcban/ChangeFormer#65]

**Comment by wgcban** [comment]
@yangjian1218 If I remember correctly, removing BN and last ReLU in the ResidualBlock resulted in better performance. Pls  check it yourself.

**Comment by yangjian1218** [comment]
> @yangjian1218 If I remember correctly, removing BN and last ReLU in the ResidualBlock resulted in better performance. Pls check it yourself.

another isuue is： in ResidualBlock，why after conv，*0.1？

**Comment by wgcban** [comment]
@yangjian1218 that is a calling factor usually adopted in many residual network implementations.

**Comment by yangjian1218** [comment]
> factor=0.1 is from this job experiment ？
