### ISSUE TITLE
Query regarding role of label images in the samples_LEVIR folder for making predictions.

### ISSUE THREAD

**Issue by SouravSarkar865** [wgcban/ChangeFormer#68]
Why are there images in the label folder for the test images?
I wanted to do predict the change between two custom images from my own dataset, so I put one image in the A folder and another in the B folder and added its name to the txt file in the list folder. After that,while running the demo_LEVIR.py file, I got an error stating there was no file corresponding to my custom images in the label folder. So I am wondering why would I need labels for making prediction. Kindly help me understand and correct me if I have interpreted it wrongly.
Thank you.

**Comment by wgcban** [comment]
@SouravSarkar865 thanks for your question. I think someone else also asked this previously. The reason why you need the label for test images are just for comparison and computing the quantitative metrics. If you don't have the actual ground truth for your testing image, replace that with a dummy image which has the same size as testing image / comment those lines which uses label in the code. Let me know if this clarifies your question.

**Comment by SouravSarkar865** [comment]
Thanks a lot for the response, it did clarify my question.
