### ISSUE TITLE
How to install requirements.txt file?

### ISSUE THREAD

**Issue by algoteam5** [wgcban/ChangeFormer#7]
How to install requirements.txt file?

**Comment by wgcban** [comment]
Hi @algoteam5 
First, create a conda environment using the following command by executing it on Linux cmd prompt:
``conda create --name ChangeFormer python=3.8.0``
For more details on how to create a conda environment in your machine refer: [Managing environments](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)

Next, activate your created environment using the following cmd:
``conda activate ChangeFormer``.

Next install all the requirements in ``requirements.txt`` inside your ``ChangeFormer`` environment using the following cmd:
``pip install -r requirements.txt``. For more details [read here](https://stackoverflow.com/questions/7225900/how-can-i-install-packages-using-pip-according-to-the-requirements-txt-file-from).

Now you are ready with your environment. Pls let me know if you have more questions.

**Comment by algoteam5** [comment]
I know how to install with pip but it seems like your `requirements` file is not in the right syntax. 

`ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 4 of requirements.txt)
`
You need two `=`, for example expat=2.2.10=h9c3ff4c_0 should be changed to expat==2.2.10=h9c3ff4c_0. And im not the the part `=h9c3ff4c_0` is neccesary

**Comment by wgcban** [comment]
Hi sorry about that - I misunderstood your question.
Note that the provided ``requirements.txt`` file can be used to create a ``conda`` virtual environment with 
``conda create --name ChangeFormer --file requirements.txt``
but this ``requirements.txt`` isn't in the right format for pip.

For more details refer to [this discussion](https://stackoverflow.com/questions/50777849/from-conda-create-requirements-txt-for-pip3). 


If you still prefer ``pip`` please find the attached [requirements.txt](https://github.com/wgcban/ChangeFormer/files/8187303/requirements.txt) that you can use to create pip virtual environment with
``
python3 -m venv env
source env/bin/activate
pip install -r requirements.txt
``
Note that in this case, packages may not be identical, so I prefer you to use conda env.

Best,
Chaminda.
