### ISSUE TITLE
the preatrain model load issue

### ISSUE THREAD

**Issue by money6651626** [wgcban/ChangeFormer#70]
Hi, I found a question that your pretrain model parameters（on ADE datasets） seem to no useful because most of the parameters do not match(the weight shape). Althought they have the same Key and load_state_dict(torch.load(self.args.pretrain), strict=False) allow it. I caculate the number of pretrain parameters which can be  loaded correctly about 6 items.

**Comment by wgcban** [comment]
@money6651626 Hi, Thanks for your question. I agree your observation. Others also raised this issue in the past, and I would like to bring your attention that, all the models provided here did not utilize the model pre-trained on ADE dataset. Instead, we first trained the model on LEVIR dataset, and then used this model as the pre-trained model when fine-tuning on other datasets such as DSIFN to speed up the training. I hope this answer clarifies your question. If you are training the model on separate dataset, you can use any of the pre-trained models provided here as the starting point which will help the faster convergence. Thanks.

**Comment by money6651626** [comment]
Sir, Are you referring to the fact that the excellent indicators on the DSIFN-CD dataset in the paper were fine-tuned on the ChangeFormerV6 version using the training results on the LEVI-CD dataset?
If so, this might not be a fair comparison for other model.

**Comment by wgcban** [comment]
https://github.com/wgcban/ChangeFormer/releases/download/v0.1.0/CD_ChangeFormerV6_LEVIR_b16_lr0.0001_adamw_train_test_200_linear_ce_multi_train_True_multi_infer_False_shuffle_AB_False_embed_dim_256.zip
