### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.CD_dataset'

### ISSUE THREAD

**Issue by arianaa30** [wgcban/ChangeFormer#71]
Why when running `python demo_LEVIR.py`, it throws this error? The file exists already.
```
    from datasets.CD_dataset import CDDataset
ModuleNotFoundError: No module named 'datasets.CD_dataset'
```

**Comment by wgcban** [comment]
@arianaa30 As you can see [here](https://github.com/wgcban/ChangeFormer/blob/a48ebede3f68ec486ca2478f137dff3b021c990b/datasets/CD_dataset.py#L97C7-L97C16) the CDDataset exists actually. Have you cloned the repo correctly. Please check and verify you have the datasets.CD_dataset file exists in your local.

**Comment by arianaa30** [comment]
We have to create a `__init.py__` file inside the dataset directory. Otherwise we can't run the code.
But I still have issues running the code on CPU. Apparently it's only working on gpu. I'm not sure how to change it to cpu...

**Comment by wgcban** [comment]
@arianaa30 I think you need to set device="cpu" instead of "cuda"
