### ISSUE TITLE
Change detection on indoor environments?

### ISSUE THREAD

**Issue by arianaa30** [wgcban/ChangeFormer#72]
I was wondering, does the pre-trained models work on indoor environments?
For instance, I want to detect the changes between these two images (door opened):

![d1](https://github.com/wgcban/ChangeFormer/assets/5509837/9f9783b9-3497-40d2-bb0b-6a86ba78d7a8)
![d2](https://github.com/wgcban/ChangeFormer/assets/5509837/eaf8acde-7198-4a11-b3a1-22edd4262537)

**Comment by wgcban** [comment]
@arianaa30 I do not think so. Because the models provided in this repo are pre-trained for building change detection. So it will not be detected general changes. You might need to fine-tune those models for your specific application.
