### ISSUE TITLE
About processed dataset download

### ISSUE THREAD

**Issue by Ozone-oo** [wgcban/ChangeFormer#73]
Hello, I always receive server errors when trying to download the processed DSIFN and LEVIR datasets(DSIFN-CD-256.zip and LEVIR-CD-256.zip in dropbox). Can you provide an alternative download method, such as Baidu Netdisk or Google Drive?

**Comment by wgcban** [comment]
@Ozone-oo Thanks for raising this issue. I have just fixed the broken links.
