### ISSUE TITLE
can't download pretrained model pt 

### ISSUE THREAD

**Issue by Busky83** [wgcban/ChangeFormer#75]
I want to test changeformer model, but i can't get the pt from https://www.dropbox.com/s/undtrlxiz7bkag5/pretrained_changeformer.pt
Where can i get the pretrained model ?

**Comment by wgcban** [comment]
@Busky83 Thanks for raising this issue. Can you pls use the GitHub link to download the pre-trained model: https://github.com/wgcban/ChangeFormer/releases/download/v0.1.0/CD_ChangeFormerV6_LEVIR_b16_lr0.0001_adamw_train_test_200_linear_ce_multi_train_True_multi_infer_False_shuffle_AB_False_embed_dim_256.zip
