### ISSUE TITLE
Some questions about image alignment

### ISSUE THREAD

**Issue by DoongLi** [wgcban/ChangeFormer#76]
Hi Chaminda, I have some questions about the dataset you use, that is, what is the accuracy of these data set images?

**Comment by wgcban** [comment]
@DoongLi Thanks for the question. The datasets used in this repo are aligned (using some pre-processing algorithm) but I have not explored the accuracy of the alignment. Based on my observations, they alignment is done pretty well, but do not have any quantitative numbers. I even haven't seen alignment accuracy in the original dataset papers.

**Comment by DoongLi** [comment]
Thank you for your reply! I am very interested in this question, I will read other papers.

**Comment by DoongLi** [comment]
By the way, have you tested your algorithm on Stree View DataSets?I want to apply Change Decetion to the robot.

**Comment by wgcban** [comment]
@DoongLi Your question is worth exploring more. No, I did not try our method on Street View Dataset.

**Comment by DoongLi** [comment]
Ok，thx

**Comment by chilin0525** [comment]
Hi @DoongLi ,
I think image alignment is important if apply this algorithm on real world scene.
Do you find other method considering image alignment in model or preprocess ?

**Comment by GRF-Sunomikp31** [comment]
Hi @chilin0525 In effect, we are creating a dataset with very accurate image alignment.

**Comment by DoongLi** [comment]
Hi @chilin0525 In effect, we are creating a dataset with very accurate image alignment.

**Comment by chilin0525** [comment]
Ok, thank you. 👍

**Comment by DoongLi** [comment]
@chilin0525  I will open about at the end of this year, I will inform you, and we can communicate again.

**Comment by hamzagorgulu** [comment]
Thanks for the great work @wgcban. I wonder if you can lead to any preprocessing algorithm to make it rotation invariant, or to use image alignment.

**Comment by DoongLi** [comment]
@hamzagorgulu  I think it very hard to achieve this.

**Comment by hamzagorgulu** [comment]
> @hamzagorgulu I think it very hard to achieve this.

Actually opencv supports this. I[mage based feature alignment](https://github.com/Crespo-dong/learnopencv/blob/master/ImageAlignment-FeatureBased/align.py) script helped me to align the input image by giving a reference image.

**Comment by DoongLi** [comment]
You can try this, but actually singe H matrix can't fine warping two images which have a big viewpoint difference.

**Comment by DoongLi** [comment]
https://github.com/IMRL/UMAD  Our dataset video have been public. @wgcban @chilin0525 @hamzagorgulu

**Comment by wgcban** [comment]
Great work! Thanks for updating here... will take a look later...

**Comment by wgcban** [comment]
Also, do you have a link to the paper?

**Comment by DoongLi** [comment]
Sorry, my tutor said the paper would not be made public until it was received.

**Comment by wgcban** [comment]
Pls post the link here when it is online.

**Comment by DoongLi** [comment]
ok

**Comment by chilin0525** [comment]
@DoongLi Hi，which labeling tool are you using ?

**Comment by DoongLi** [comment]
@chilin0525 This, https://github.com/CVHub520/X-AnyLabeling
