### ISSUE TITLE
Calculation of evaluation index

### ISSUE THREAD

**Issue by For-Isolate** [wgcban/ChangeFormer#78]
Hello, may I ask how the precision, iou and f1 score of changeformer v6 are calculated? I use the Levi-CD dataset to load the best_ckpt provided by you. The average values of precision, iou and f1 score of the variation categories are 70, 60 and 75 respectively, but the values in your paper are 92, 82 and 90, which are quite different from the results I got. My email is 1972219282@qq.com, and I hope to communicate with you further

**Comment by wgcban** [comment]
@For-Isolate I think there is some problem with your setup. 

- First, examine the visual quality of results. Do they look good?
- Check you are loading correct pre-trained model.
- Check you are using pre-processed dataset provided in the readme file.
- If everything above fails, try to train the model yourself.

**Comment by For-Isolate** [comment]
I have read your code carefully, in which precision, iou and f1 score calculated the unchanged category and the changed category respectively. May I ask how these evaluation indicators in your article were calculated according to this result

**Comment by wgcban** [comment]
@For-Isolate Yes, the reported values are evaluated for the pre-trained models provided here: https://github.com/wgcban/ChangeFormer/releases/tag/v0.1.0 and it has been validated by other researchers as well. 

Did you check the visualizations? How they look?

**Comment by For-Isolate** [comment]
As for the calculation of evaluation indicators, my doubts are as follows. Assume that the unchanged class is "a" and the changing class is "b". Except for OA, each evaluation indicator has a score_a and score_b, such as precision_a and precision_b, or recall_a and recall_b, as well as f1 score and IoU. However, in all the papers on change detection I have read, including yours, there is only one value in the table of experimental results. May I ask how the single value in the table is calculated according to the two types of values? Is the weight calculated according to the proportion of the number of pixels, and then the weighted sum is obtained? Look forward to your answer, thank you

**Comment by wgcban** [comment]
@For-Isolate Thanks for clarifying your question again. I think, now I understand your question well.

Since, in change detection, we are interested in detecting changes, the we usually report main metrics (such as precision, recall, F1, and IoU) with resect to the change class as mentioned in Sec. 3.3 of the paper. 
![image](https://github.com/wgcban/ChangeFormer/assets/38159198/6c337231-1d9f-4f17-819c-a2f4ddd203b9)

**Comment by wgcban** [comment]
@For-Isolate lmk if I answer your question, so I can close this issue.

**Comment by wgcban** [comment]
@For-Isolate Since I did not hear from you -- I assume this issue has been resolved. Hence, closing the issue.
