### ISSUE TITLE
Hello, If I use my own dataset for training, how should I generate files in the list folder?

### ISSUE THREAD

**Issue by wangqingl** [wgcban/ChangeFormer#82]

**Comment by wangqingl** [comment]
![image](https://github.com/wgcban/ChangeFormer/assets/102707449/3d21f028-4169-4518-9c12-1c0d1b7bb21c)
There are only the first three folders on the graph in my dataset

**Comment by hamzagorgulu** [comment]
You can read all of the filenames with glob module of python and then split the list slicing. Then save them as train.txt and test.txt

**Comment by wangqingl** [comment]
> You can read all of the filenames with glob module of python and then split the list slicing. Then save them as train.txt and test.txt

Thank you for your reply. I try it.

**Comment by wgcban** [comment]
> You can read all of the filenames with glob module of python and then split the list slicing. Then save them as train.txt and test.txt
@hamzagorgulu 
Thank you for your answer!
