### ISSUE TITLE
Hello, Why does your pre trained model occupy over 460 megabytes of memory, while mine only has over 60 megabytes

### ISSUE THREAD

**Issue by wangqingl** [wgcban/ChangeFormer#83]
![image](https://github.com/wgcban/ChangeFormer/assets/102707449/7dd94193-2472-425e-8a36-175f30da46e9)
![image](https://github.com/wgcban/ChangeFormer/assets/102707449/1a816dd4-7f54-49a2-a8d3-456786552104)

**Comment by wgcban** [comment]
Same test performance?

**Comment by wangqingl** [comment]
> @wangqingl Same test performance?

Hello, When I modified the model path in demo_LEVIR.py file encountered the following error while testing the model I trained. What should I do?
![image](https://github.com/wgcban/ChangeFormer/assets/102707449/feea56aa-5317-4528-94b4-cf97130fd47d)

**Comment by wangqingl** [comment]
RuntimeError: Error(s) in loading state_dict for ChangeFormerV6:
	Missing key(s) in state_dict: "Tenc_x2.patch_embed1.proj.weight", "Tenc_x2.patch_embed1.proj.bias", "Tenc_x2.patch_embed1.norm.weight", "Tenc_x2.patch_embed1.norm.bias", "Tenc_x2.patch_embed2.proj.weight", "Tenc_x2.patch_embed2.proj.bias", "Tenc_x2.patch_embed2.norm.weight", "Tenc_x2.patch_embed2.norm.bias", "Tenc_x2.patch_embed3.proj.weight", "Tenc_x2.patch_embed3.proj.bias", "Tenc_x2.patch_embed3.norm.weight", "Tenc_x2.patch_embed3.norm.bias", "Tenc_x2.patch_embed4.proj.weight", "Tenc_x2.patch_embed4.proj.bias", "Tenc_x2.patch_embed4.norm.weight", "Tenc_x2.patch_embed4.norm.bias", "Tenc_x2.block1.0.norm1.weight", "Tenc_x2.block1.0.norm1.bias", "Tenc_x2.block1.0.attn.q.weight", "Tenc_x2.block1.0.attn.q.bias", "Tenc_x2.block1.0.attn.kv.weight", "Tenc_x2.block1.0.attn.kv.bias", "Tenc_x2.block1.0.attn.proj.weight", "Tenc_x2.block1.0.attn.proj.bias", "Tenc_x2.block1.0.attn.sr.weight", "Tenc_x2.block1.0.attn.sr.bias", "Tenc_x2.block1.0.attn.norm.weight", "Tenc_x2.block1.0.attn.norm.bias", "Tenc_x2.block1.0.norm2.weight", "Tenc_x2.block1.0.norm2.bias", "Tenc_x2.block1.0.mlp.fc1.weight", "Tenc_x2.block1.0.mlp.fc1.bias", "Tenc_x2.block1.0.mlp.dwconv.dwconv.weight", "Tenc_x2.block1.0.mlp.dwconv.dwconv.bias", "Tenc_x2.block1.0.mlp.fc2.weight", "Tenc_x2.block1.0.mlp.fc2.bias", "Tenc_x2.block1.1.norm1.weight", "Tenc_x2.block1.1.norm1.bias", "Tenc_x2.block1.1.attn.q.weight", "Tenc_x2.block1.1.attn.q.bias", "Tenc_x2.block1.1.attn.kv.weight", "Tenc_x2.block1.1.attn.kv.bias", "Tenc_x2.block1.1.attn.proj.weight", "Tenc_x2.block1.1.attn.proj.bias", "Tenc_x2.block1.1.attn.sr.weight", "Tenc_x2.block1.1.attn.sr.bias", "Tenc_x2.block1.1.attn.norm.weight", "Tenc_x2.block1.1.attn.norm.bias", "Tenc_x2.block1.1.norm2.weight", "Tenc_x2.block1.1.norm2.bias", "Tenc_x2.block1.1.mlp.fc1.weight", "Tenc_x2.block1.1.mlp.fc1.bias", "Tenc_x2.block1.1.mlp.dwconv.dwconv.weight", "Tenc_x2.block1.1.mlp.dwconv.dwconv.bias", "Tenc_x2.block1.1.mlp.fc2.weight", "Tenc_x2.block1.1.mlp.fc2.bias", "Tenc_x2.block1.2.norm1.weight", "Tenc_x2.block1.2.norm1.bias", "Tenc_x2.block1.2.attn.q.weight", "Tenc_x2.block1.2.attn.q.bias", "Tenc_x2.block1.2.attn.kv.weight", "Tenc_x2.block1.2.attn.kv.bias", "Tenc_x2.block1.2.attn.proj.weight", "Tenc_x2.block1.2.attn.proj.bias", "Tenc_x2.block1.2.attn.sr.weight", "Tenc_x2.block1.2.attn.sr.bias", "Tenc_x2.block1.2.attn.norm.weight", "Tenc_x2.block1.2.attn.norm.bias", "Tenc_x2.block1.2.norm2.weight", "Tenc_x2.block1.2.norm2.bias", "Tenc_x2.block1.2.mlp.fc1.weight", "Tenc_x2.block1.2.mlp.fc1.bias", "Tenc_x2.block1.2.mlp.dwconv.dwconv.weight", "Tenc_x2.block1.2.mlp.dwconv.dwconv.bias", "Tenc_x2.block1.2.mlp.fc2.weight", "Tenc_x2.block1.2.mlp.fc2.bias", "Tenc_x2.norm1.weight", "Tenc_x2.norm1.bias", "Tenc_x2.block2.0.norm1.weight", "Tenc_x2.block2.0.norm1.bias", "Tenc_x2.block2.0.attn.q.weight", "Tenc_x2.block2.0.attn.q.bias", "Tenc_x2.block2.0.attn.kv.weight", "Tenc_x2.block2.0.attn.kv.bias", "Tenc_x2.block2.0.attn.proj.weight", "Tenc_x2.block2.0.attn.proj.bias", "Tenc_x2.block2.0.attn.sr.weight", "Tenc_x2.block2.0.attn.sr.bias", "Tenc_x2.block2.0.attn.norm.weight", "Tenc_x2.block2.0.attn.norm.bias", "Tenc_x2.block2.0.norm2.weight", "Tenc_x2.block2.0.norm2.bias", "Tenc_x2.block2.0.mlp.fc1.weight", "Tenc_x2.block2.0.mlp.fc1.bias", "Tenc_x2.block2.0.mlp.dwconv.dwconv.weight", "Tenc_x2.block2.0.mlp.dwconv.dwconv.bias", "Tenc_x2.block2.0.mlp.fc2.weight", "Tenc_x2.block2.0.mlp.fc2.bias", "Tenc_x2.block2.1.norm1.weight", "Tenc_x2.block2.1.norm1.bias", "Tenc_x2.block2.1.attn.q.weight", "Tenc_x2.block2.1.attn.q.bias", "Tenc_x2.block2.1.attn.kv.weight", "Tenc_x2.block2.1.attn.kv.bias", "Tenc_x2.block2.1.attn.proj.weight", "Tenc_x2.block2.1.attn.proj.bias", "Tenc_x2.block2.1.attn.sr.weight", "Tenc_x2.block2.1.attn.sr.bias", "Tenc_x2.block2.1.attn.norm.weight", "Tenc_x2.block2.1.attn.norm.bias", "Tenc_x2.block2.1.norm2.weight", "Tenc_x2.block2.1.norm2.bias", "Tenc_x2.block2.1.mlp.fc1.weight", "Tenc_x2.block2.1.mlp.fc1.bias", "Tenc_x2.block2.1.mlp.dwconv.dwconv.weight", "Tenc_x2.block2.1.mlp.dwconv.dwconv.bias", "Tenc_x2.block2.1.mlp.fc2.weight", "Tenc_x2.block2.1.mlp.fc2.bias", "Tenc_x2.block2.2.norm1.weight", "Tenc_x2.block2.2.norm1.bias", "Tenc_x2.block2.2.attn.q.weight", "Tenc_x2.block2.2.attn.q.bias", "Tenc_x2.block2.2.attn.kv.weight", "Tenc_x2.block2.2.attn.kv.bias", "Tenc_x2.block2.2.attn.proj.weight", "Tenc_x2.block2.2.attn.proj.bias", "Tenc_x2.block2.2.attn.sr.weight", "Tenc_x2.block2.2.attn.sr.bias", "Tenc_x2.block2.2.attn.norm.weight", "Tenc_x2.block2.2.attn.norm.bias", "Tenc_x2.block2.2.norm2.weight", "Tenc_x2.block2.2.norm2.bias", "Tenc_x2.block2.2.mlp.fc1.weight", "Tenc_x2.block2.2.mlp.fc1.bias", "Tenc_x2.block2.2.mlp.dwconv.dwconv.weight", "Tenc_x2.block2.2.mlp.dwconv.dwconv.bias", "Tenc_x2.block2.2.mlp.fc2.weight", "Tenc_x2.block2.2.mlp.fc2.bias", "Tenc_x2.norm2.weight", "Tenc_x2.norm2.bias", "Tenc_x2.block3.0.norm1.weight", "Tenc_x2.block3.0.norm1.bias", "Tenc_x2.block3.0.attn.q.weight", "Tenc_x2.block3.0.attn.q.bias", "Tenc_x2.block3.0.attn.kv.weight", "Tenc_x2.block3.0.attn.kv.bias", "Tenc_x2.block3.0.attn.proj.weight", "Tenc_x2.block3.0.attn.proj.bias", "Tenc_x2.block3.0.attn.sr.weight", "Tenc_x2.block3.0.attn.sr.bias", "Tenc_x2.block3.0.attn.norm.weight", "Tenc_x2.block3.0.attn.norm.bias", "Tenc_x2.block3.0.norm2.weight", "Tenc_x2.block3.0.norm2.bias", "Tenc_x2.block3.0.mlp.fc1.weight", "Tenc_x2.block3.0.mlp.fc1.bias", "Tenc_x2.block3.0.mlp.dwconv.dwconv.weight", "Tenc_x2.block3.0.mlp.dwconv.dwconv.bias", "Tenc_x2.block3.0.mlp.fc2.weight", "Tenc_x2.block3.0.mlp.fc2.bias", "Tenc_x2.block3.1.norm1.weight", "Tenc_x2.block3.1.norm1.bias", "Tenc_x2.block3.1.attn.q.weight", "Tenc_x2.block3.1.attn.q.bias", "Tenc_x2.block3.1.attn.kv.weight", "Tenc_x2.block3.1.attn.kv.bias", "Tenc_x2.block3.1.attn.proj.weight", "Tenc_x2.block3.1.attn.proj.bias", "Tenc_x2.block3.1.attn.sr.weight", "Tenc_x2.block3.1.attn.sr.bias", "Tenc_x2.block3.1.attn.norm.weight", "Tenc_x2.block3.1.attn.norm.bias", "Tenc_x2.block3.1.norm2.weight", "Tenc_x2.block3.1.norm2.bias", "Tenc_x2.block3.1.mlp.fc1.weight", "Tenc_x2.block3.1.mlp.fc1.bias", "Tenc_x2.block3.1.mlp.dwconv.dwconv.weight", "Tenc_x2.block3.1.mlp.dwconv.dwconv.bias", "Tenc_x2.block3.1.mlp.fc2.weight", "Tenc_x2.block3.1.mlp.fc2.bias", "Tenc_x2.block3.2.norm1.weight", "Tenc_x2.block3.2.norm1.bias", "Tenc_x2.block3.2.attn.q.weight", "Tenc_x2.block3.2.attn.q.bias", "Tenc_x2.block3.2.attn.kv.weight", "Tenc_x2.block3.2.attn.kv.bias", "Tenc_x2.block3.2.attn.proj.weight", "Tenc_x2.block3.2.attn.proj.bias", "Tenc_x2.block3.2.attn.sr.weight", "Tenc_x2.block3.2.attn.sr.bias", "Tenc_x2.block3.2.attn.norm.weight", "Tenc_x2.block3.2.attn.norm.bias", "Tenc_x2.block3.2.norm2.weight", "Tenc_x2.block3.2.norm2.bias", "Tenc_x2.block3.2.mlp.fc1.weight", "Tenc_x2.block3.2.mlp.fc1.bias", "Tenc_x2.block3.2.mlp.dwconv.dwconv.weight", "Tenc_x2.block3.2.mlp.dwconv.dwconv.bias", "Tenc_x2.block3.2.mlp.fc2.weight", "Tenc_x2.block3.2.mlp.fc2.bias", "Tenc_x2.block3.3.norm1.weight", "Tenc_x2.block3.3.norm1.bias", "Tenc_x2.block3.3.attn.q.weight", "Tenc_x2.block3.3.attn.q.bias", "Tenc_x2.block3.3.attn.kv.weight", "Tenc_x2.block3.3.attn.kv.bias", "Tenc_x2.block3.3.attn.proj.weight", "Tenc_x2.block3.3.attn.proj.bias", "Tenc_x2.block3.3.attn.sr.weight", "Tenc_x2.block3.3.attn.sr.bias", "Tenc_x2.block3.3.attn.norm.weight", "Tenc_x2.block3.3.attn.norm.bias", "Tenc_x2.block3.3.norm2.weight", "Tenc_x2.block3.3.norm2.bias", "Tenc_x2.block3.3.mlp.fc1.weight", "Tenc_x2.block3.3.mlp.fc1.bias", "Tenc_x2.block3.3.mlp.dwconv.dwconv.weight", "Tenc_x2.block3.3.mlp.dwconv.dwconv.bias", "Tenc_x2.block3.3.mlp.fc2.weight", "Tenc_x2.block3.3.mlp.fc2.bias", "Tenc_x2.norm3.weight", "Tenc_x2.norm3.bias", "Tenc_x2.block4.0.norm1.weight", "Tenc_x2.block4.0.norm1.bias", "Tenc_x2.block4.0.attn.q.weight", "Tenc_x2.block4.0.attn.q.bias", "Tenc_x2.block4.0.attn.kv.weight", "Tenc_x2.block4.0.attn.kv.bias", "Tenc_x2.block4.0.attn.proj.weight", "Tenc_x2.block4.0.attn.proj.bias", "Tenc_x2.block4.0.norm2.weight", "Tenc_x2.block4.0.norm2.bias", "Tenc_x2.block4.0.mlp.fc1.weight", "Tenc_x2.block4.0.mlp.fc1.bias", "Tenc_x2.block4.0.mlp.dwconv.dwconv.weight", "Tenc_x2.block4.0.mlp.dwconv.dwconv.bias", "Tenc_x2.block4.0.mlp.fc2.weight", "Tenc_x2.block4.0.mlp.fc2.bias", "Tenc_x2.block4.1.norm1.weight", "Tenc_x2.block4.1.norm1.bias", "Tenc_x2.block4.1.attn.q.weight", "Tenc_x2.block4.1.attn.q.bias", "Tenc_x2.block4.1.attn.kv.weight", "Tenc_x2.block4.1.attn.kv.bias", "Tenc_x2.block4.1.attn.proj.weight", "Tenc_x2.block4.1.attn.proj.bias", "Tenc_x2.block4.1.norm2.weight", "Tenc_x2.block4.1.norm2.bias", "Tenc_x2.block4.1.mlp.fc1.weight", "Tenc_x2.block4.1.mlp.fc1.bias", "Tenc_x2.block4.1.mlp.dwconv.dwconv.weight", "Tenc_x2.block4.1.mlp.dwconv.dwconv.bias", "Tenc_x2.block4.1.mlp.fc2.weight", "Tenc_x2.block4.1.mlp.fc2.bias", "Tenc_x2.block4.2.norm1.weight", "Tenc_x2.block4.2.norm1.bias", "Tenc_x2.block4.2.attn.q.weight", "Tenc_x2.block4.2.attn.q.bias", "Tenc_x2.block4.2.attn.kv.weight", "Tenc_x2.block4.2.attn.kv.bias", "Tenc_x2.block4.2.attn.proj.weight", "Tenc_x2.block4.2.attn.proj.bias", "Tenc_x2.block4.2.norm2.weight", "Tenc_x2.block4.2.norm2.bias", "Tenc_x2.block4.2.mlp.fc1.weight", "Tenc_x2.block4.2.mlp.fc1.bias", "Tenc_x2.block4.2.mlp.dwconv.dwconv.weight", "Tenc_x2.block4.2.mlp.dwconv.dwconv.bias", "Tenc_x2.block4.2.mlp.fc2.weight", "Tenc_x2.block4.2.mlp.fc2.bias", "Tenc_x2.norm4.weight", "Tenc_x2.norm4.bias", "TDec_x2.linear_c4.proj.weight", "TDec_x2.linear_c4.proj.bias", "TDec_x2.linear_c3.proj.weight", "TDec_x2.linear_c3.proj.bias", "TDec_x2.linear_c2.proj.weight", "TDec_x2.linear_c2.proj.bias", "TDec_x2.linear_c1.proj.weight", "TDec_x2.linear_c1.proj.bias", "TDec_x2.diff_c4.0.weight", "TDec_x2.diff_c4.0.bias", "TDec_x2.diff_c4.2.weight", "TDec_x2.diff_c4.2.bias", "TDec_x2.diff_c4.2.running_mean", "TDec_x2.diff_c4.2.running_var", "TDec_x2.diff_c4.3.weight", "TDec_x2.diff_c4.3.bias", "TDec_x2.diff_c3.0.weight", "TDec_x2.diff_c3.0.bias", "TDec_x2.diff_c3.2.weight", "TDec_x2.diff_c3.2.bias", "TDec_x2.diff_c3.2.running_mean", "TDec_x2.diff_c3.2.running_var", "TDec_x2.diff_c3.3.weight", "TDec_x2.diff_c3.3.bias", "TDec_x2.diff_c2.0.weight", "TDec_x2.diff_c2.0.bias", "TDec_x2.diff_c2.2.weight", "TDec_x2.diff_c2.2.bias", "TDec_x2.diff_c2.2.running_mean", "TDec_x2.diff_c2.2.running_var", "TDec_x2.diff_c2.3.weight", "TDec_x2.diff_c2.3.bias", "TDec_x2.diff_c1.0.weight", "TDec_x2.diff_c1.0.bias", "TDec_x2.diff_c1.2.weight", "TDec_x2.diff_c1.2.bias", "TDec_x2.diff_c1.2.running_mean", "TDec_x2.diff_c1.2.running_var", "TDec_x2.diff_c1.3.weight", "TDec_x2.diff_c1.3.bias", "TDec_x2.make_pred_c4.0.weight", "TDec_x2.make_pred_c4.0.bias", "TDec_x2.make_pred_c4.2.weight", "TDec_x2.make_pred_c4.2.bias", "TDec_x2.make_pred_c4.2.running_mean", "TDec_x2.make_pred_c4.2.running_var", "TDec_x2.make_pred_c4.3.weight", "TDec_x2.make_pred_c4.3.bias", "TDec_x2.make_pred_c3.0.weight", "TDec_x2.make_pred_c3.0.bias", "TDec_x2.make_pred_c3.2.weight", "TDec_x2.make_pred_c3.2.bias", "TDec_x2.make_pred_c3.2.running_mean", "TDec_x2.make_pred_c3.2.running_var", "TDec_x2.make_pred_c3.3.weight", "TDec_x2.make_pred_c3.3.bias", "TDec_x2.make_pred_c2.0.weight", "TDec_x2.make_pred_c2.0.bias", "TDec_x2.make_pred_c2.2.weight", "TDec_x2.make_pred_c2.2.bias", "TDec_x2.make_pred_c2.2.running_mean", "TDec_x2.make_pred_c2.2.running_var", "TDec_x2.make_pred_c2.3.weight", "TDec_x2.make_pred_c2.3.bias", "TDec_x2.make_pred_c1.0.weight", "TDec_x2.make_pred_c1.0.bias", "TDec_x2.make_pred_c1.2.weight", "TDec_x2.make_pred_c1.2.bias", "TDec_x2.make_pred_c1.2.running_mean", "TDec_x2.make_pred_c1.2.running_var", "TDec_x2.make_pred_c1.3.weight", "TDec_x2.make_pred_c1.3.bias", "TDec_x2.linear_fuse.0.weight", "TDec_x2.linear_fuse.0.bias", "TDec_x2.linear_fuse.1.weight", "TDec_x2.linear_fuse.1.bias", "TDec_x2.linear_fuse.1.running_mean", "TDec_x2.linear_fuse.1.running_var", "TDec_x2.convd2x.conv2d.weight", "TDec_x2.convd2x.conv2d.bias", "TDec_x2.dense_2x.0.conv1.conv2d.weight", "TDec_x2.dense_2x.0.conv1.conv2d.bias", "TDec_x2.dense_2x.0.conv2.conv2d.weight", "TDec_x2.dense_2x.0.conv2.conv2d.bias", "TDec_x2.convd1x.conv2d.weight", "TDec_x2.convd1x.conv2d.bias", "TDec_x2.dense_1x.0.conv1.conv2d.weight", "TDec_x2.dense_1x.0.conv1.conv2d.bias", "TDec_x2.dense_1x.0.conv2.conv2d.weight", "TDec_x2.dense_1x.0.conv2.conv2d.bias", "TDec_x2.change_probability.conv2d.weight", "TDec_x2.change_probability.conv2d.bias". 
	Unexpected key(s) in state_dict: "pos_embedding", "resnet.conv1.weight", "resnet.bn1.weight", "resnet.bn1.bias", "resnet.bn1.running_mean", "resnet.bn1.running_var", "resnet.bn1.num_batches_tracked", "resnet.layer1.0.conv1.weight", "resnet.layer1.0.bn1.weight", "resnet.layer1.0.bn1.bias", "resnet.layer1.0.bn1.running_mean", "resnet.layer1.0.bn1.running_var", "resnet.layer1.0.bn1.num_batches_tracked", "resnet.layer1.0.conv2.weight", "resnet.layer1.0.bn2.weight", "resnet.layer1.0.bn2.bias", "resnet.layer1.0.bn2.running_mean", "resnet.layer1.0.bn2.running_var", "resnet.layer1.0.bn2.num_batches_tracked", "resnet.layer1.1.conv1.weight", "resnet.layer1.1.bn1.weight", "resnet.layer1.1.bn1.bias", "resnet.layer1.1.bn1.running_mean", "resnet.layer1.1.bn1.running_var", "resnet.layer1.1.bn1.num_batches_tracked", "resnet.layer1.1.conv2.weight", "resnet.layer1.1.bn2.weight", "resnet.layer1.1.bn2.bias", "resnet.layer1.1.bn2.running_mean", "resnet.layer1.1.bn2.running_var", "resnet.layer1.1.bn2.num_batches_tracked", "resnet.layer2.0.conv1.weight", "resnet.layer2.0.bn1.weight", "resnet.layer2.0.bn1.bias", "resnet.layer2.0.bn1.running_mean", "resnet.layer2.0.bn1.running_var", "resnet.layer2.0.bn1.num_batches_tracked", "resnet.layer2.0.conv2.weight", "resnet.layer2.0.bn2.weight", "resnet.layer2.0.bn2.bias", "resnet.layer2.0.bn2.running_mean", "resnet.layer2.0.bn2.running_var", "resnet.layer2.0.bn2.num_batches_tracked", "resnet.layer2.0.downsample.0.weight", "resnet.layer2.0.downsample.1.weight", "resnet.layer2.0.downsample.1.bias", "resnet.layer2.0.downsample.1.running_mean", "resnet.layer2.0.downsample.1.running_var", "resnet.layer2.0.downsample.1.num_batches_tracked", "resnet.layer2.1.conv1.weight", "resnet.layer2.1.bn1.weight", "resnet.layer2.1.bn1.bias", "resnet.layer2.1.bn1.running_mean", "resnet.layer2.1.bn1.running_var", "resnet.layer2.1.bn1.num_batches_tracked", "resnet.layer2.1.conv2.weight", "resnet.layer2.1.bn2.weight", "resnet.layer2.1.bn2.bias", "resnet.layer2.1.bn2.running_mean", "resnet.layer2.1.bn2.running_var", "resnet.layer2.1.bn2.num_batches_tracked", "resnet.layer3.0.conv1.weight", "resnet.layer3.0.bn1.weight", "resnet.layer3.0.bn1.bias", "resnet.layer3.0.bn1.running_mean", "resnet.layer3.0.bn1.running_var", "resnet.layer3.0.bn1.num_batches_tracked", "resnet.layer3.0.conv2.weight", "resnet.layer3.0.bn2.weight", "resnet.layer3.0.bn2.bias", "resnet.layer3.0.bn2.running_mean", "resnet.layer3.0.bn2.running_var", "resnet.layer3.0.bn2.num_batches_tracked", "resnet.layer3.0.downsample.0.weight", "resnet.layer3.0.downsample.1.weight", "resnet.layer3.0.downsample.1.bias", "resnet.layer3.0.downsample.1.running_mean", "resnet.layer3.0.downsample.1.running_var", "resnet.layer3.0.downsample.1.num_batches_tracked", "resnet.layer3.1.conv1.weight", "resnet.layer3.1.bn1.weight", "resnet.layer3.1.bn1.bias", "resnet.layer3.1.bn1.running_mean", "resnet.layer3.1.bn1.running_var", "resnet.layer3.1.bn1.num_batches_tracked", "resnet.layer3.1.conv2.weight", "resnet.layer3.1.bn2.weight", "resnet.layer3.1.bn2.bias", "resnet.layer3.1.bn2.running_mean", "resnet.layer3.1.bn2.running_var", "resnet.layer3.1.bn2.num_batches_tracked", "resnet.layer4.0.conv1.weight", "resnet.layer4.0.bn1.weight", "resnet.layer4.0.bn1.bias", "resnet.layer4.0.bn1.running_mean", "resnet.layer4.0.bn1.running_var", "resnet.layer4.0.bn1.num_batches_tracked", "resnet.layer4.0.conv2.weight", "resnet.layer4.0.bn2.weight", "resnet.layer4.0.bn2.bias", "resnet.layer4.0.bn2.running_mean", "resnet.layer4.0.bn2.running_var", "resnet.layer4.0.bn2.num_batches_tracked", "resnet.layer4.0.downsample.0.weight", "resnet.layer4.0.downsample.1.weight", "resnet.layer4.0.downsample.1.bias", "resnet.layer4.0.downsample.1.running_mean", "resnet.layer4.0.downsample.1.running_var", "resnet.layer4.0.downsample.1.num_batches_tracked", "resnet.layer4.1.conv1.weight", "resnet.layer4.1.bn1.weight", "resnet.layer4.1.bn1.bias", "resnet.layer4.1.bn1.running_mean", "resnet.layer4.1.bn1.running_var", "resnet.layer4.1.bn1.num_batches_tracked", "resnet.layer4.1.conv2.weight", "resnet.layer4.1.bn2.weight", "resnet.layer4.1.bn2.bias", "resnet.layer4.1.bn2.running_mean", "resnet.layer4.1.bn2.running_var", "resnet.layer4.1.bn2.num_batches_tracked", "resnet.fc.weight", "resnet.fc.bias", "classifier.0.weight", "classifier.1.weight", "classifier.1.bias", "classifier.1.running_mean", "classifier.1.running_var", "classifier.1.num_batches_tracked", "classifier.3.weight", "classifier.3.bias", "conv_pred.weight", "conv_pred.bias", "conv_a.weight", "transformer.layers.0.0.fn.norm.weight", "transformer.layers.0.0.fn.norm.bias", "transformer.layers.0.0.fn.fn.to_qkv.weight", "transformer.layers.0.0.fn.fn.to_out.0.weight", "transformer.layers.0.0.fn.fn.to_out.0.bias", "transformer.layers.0.1.fn.norm.weight", "transformer.layers.0.1.fn.norm.bias", "transformer.layers.0.1.fn.fn.net.0.weight", "transformer.layers.0.1.fn.fn.net.0.bias", "transformer.layers.0.1.fn.fn.net.3.weight", "transformer.layers.0.1.fn.fn.net.3.bias", "transformer_decoder.layers.0.0.fn.norm.weight", "transformer_decoder.layers.0.0.fn.norm.bias", "transformer_decoder.layers.0.0.fn.fn.to_q.weight", "transformer_decoder.layers.0.0.fn.fn.to_k.weight", "transformer_decoder.layers.0.0.fn.fn.to_v.weight", "transformer_decoder.layers.0.0.fn.fn.to_out.0.weight", "transformer_decoder.layers.0.0.fn.fn.to_out.0.bias", "transformer_decoder.layers.0.1.fn.norm.weight", "transformer_decoder.layers.0.1.fn.norm.bias", "transformer_decoder.layers.0.1.fn.fn.net.0.weight", "transformer_decoder.layers.0.1.fn.fn.net.0.bias", "transformer_decoder.layers.0.1.fn.fn.net.3.weight", "transformer_decoder.layers.0.1.fn.fn.net.3.bias", "transformer_decoder.layers.1.0.fn.norm.weight", "transformer_decoder.layers.1.0.fn.norm.bias", "transformer_decoder.layers.1.0.fn.fn.to_q.weight", "transformer_decoder.layers.1.0.fn.fn.to_k.weight", "transformer_decoder.layers.1.0.fn.fn.to_v.weight", "transformer_decoder.layers.1.0.fn.fn.to_out.0.weight", "transformer_decoder.layers.1.0.fn.fn.to_out.0.bias", "transformer_decoder.layers.1.1.fn.norm.weight", "transformer_decoder.layers.1.1.fn.norm.bias", "transformer_decoder.layers.1.1.fn.fn.net.0.weight", "transformer_decoder.layers.1.1.fn.fn.net.0.bias", "transformer_decoder.layers.1.1.fn.fn.net.3.weight", "transformer_decoder.layers.1.1.fn.fn.net.3.bias", "transformer_decoder.layers.2.0.fn.norm.weight", "transformer_decoder.layers.2.0.fn.norm.bias", "transformer_decoder.layers.2.0.fn.fn.to_q.weight", "transformer_decoder.layers.2.0.fn.fn.to_k.weight", "transformer_decoder.layers.2.0.fn.fn.to_v.weight", "transformer_decoder.layers.2.0.fn.fn.to_out.0.weight", "transformer_decoder.layers.2.0.fn.fn.to_out.0.bias", "transformer_decoder.layers.2.1.fn.norm.weight", "transformer_decoder.layers.2.1.fn.norm.bias", "transformer_decoder.layers.2.1.fn.fn.net.0.weight", "transformer_decoder.layers.2.1.fn.fn.net.0.bias", "transformer_decoder.layers.2.1.fn.fn.net.3.weight", "transformer_decoder.layers.2.1.fn.fn.net.3.bias", "transformer_decoder.layers.3.0.fn.norm.weight", "transformer_decoder.layers.3.0.fn.norm.bias", "transformer_decoder.layers.3.0.fn.fn.to_q.weight", "transformer_decoder.layers.3.0.fn.fn.to_k.weight", "transformer_decoder.layers.3.0.fn.fn.to_v.weight", "transformer_decoder.layers.3.0.fn.fn.to_out.0.weight", "transformer_decoder.layers.3.0.fn.fn.to_out.0.bias", "transformer_decoder.layers.3.1.fn.norm.weight", "transformer_decoder.layers.3.1.fn.norm.bias", "transformer_decoder.layers.3.1.fn.fn.net.0.weight", "transformer_decoder.layers.3.1.fn.fn.net.0.bias", "transformer_decoder.layers.3.1.fn.fn.net.3.weight", "transformer_decoder.layers.3.1.fn.fn.net.3.bias", "transformer_decoder.layers.4.0.fn.norm.weight", "transformer_decoder.layers.4.0.fn.norm.bias", "transformer_decoder.layers.4.0.fn.fn.to_q.weight", "transformer_decoder.layers.4.0.fn.fn.to_k.weight", "transformer_decoder.layers.4.0.fn.fn.to_v.weight", "transformer_decoder.layers.4.0.fn.fn.to_out.0.weight", "transformer_decoder.layers.4.0.fn.fn.to_out.0.bias", "transformer_decoder.layers.4.1.fn.norm.weight", "transformer_decoder.layers.4.1.fn.norm.bias", "transformer_decoder.layers.4.1.fn.fn.net.0.weight", "transformer_decoder.layers.4.1.fn.fn.net.0.bias", "transformer_decoder.layers.4.1.fn.fn.net.3.weight", "transformer_decoder.layers.4.1.fn.fn.net.3.bias", "transformer_decoder.layers.5.0.fn.norm.weight", "transformer_decoder.layers.5.0.fn.norm.bias", "transformer_decoder.layers.5.0.fn.fn.to_q.weight", "transformer_decoder.layers.5.0.fn.fn.to_k.weight", "transformer_decoder.layers.5.0.fn.fn.to_v.weight", "transformer_decoder.layers.5.0.fn.fn.to_out.0.weight", "transformer_decoder.layers.5.0.fn.fn.to_out.0.bias", "transformer_decoder.layers.5.1.fn.norm.weight", "transformer_decoder.layers.5.1.fn.norm.bias", "transformer_decoder.layers.5.1.fn.fn.net.0.weight", "transformer_decoder.layers.5.1.fn.fn.net.0.bias", "transformer_decoder.layers.5.1.fn.fn.net.3.weight", "transformer_decoder.layers.5.1.fn.fn.net.3.bias", "transformer_decoder.layers.6.0.fn.norm.weight", "transformer_decoder.layers.6.0.fn.norm.bias", "transformer_decoder.layers.6.0.fn.fn.to_q.weight", "transformer_decoder.layers.6.0.fn.fn.to_k.weight", "transformer_decoder.layers.6.0.fn.fn.to_v.weight", "transformer_decoder.layers.6.0.fn.fn.to_out.0.weight", "transformer_decoder.layers.6.0.fn.fn.to_out.0.bias", "transformer_decoder.layers.6.1.fn.norm.weight", "transformer_decoder.layers.6.1.fn.norm.bias", "transformer_decoder.layers.6.1.fn.fn.net.0.weight", "transformer_decoder.layers.6.1.fn.fn.net.0.bias", "transformer_decoder.layers.6.1.fn.fn.net.3.weight", "transformer_decoder.layers.6.1.fn.fn.net.3.bias", "transformer_decoder.layers.7.0.fn.norm.weight", "transformer_decoder.layers.7.0.fn.norm.bias", "transformer_decoder.layers.7.0.fn.fn.to_q.weight", "transformer_decoder.layers.7.0.fn.fn.to_k.weight", "transformer_decoder.layers.7.0.fn.fn.to_v.weight", "transformer_decoder.layers.7.0.fn.fn.to_out.0.weight", "transformer_decoder.layers.7.0.fn.fn.to_out.0.bias", "transformer_decoder.layers.7.1.fn.norm.weight", "transformer_decoder.layers.7.1.fn.norm.bias", "transformer_decoder.layers.7.1.fn.fn.net.0.weight", "transformer_decoder.layers.7.1.fn.fn.net.0.bias", "transformer_decoder.layers.7.1.fn.fn.net.3.weight", "transformer_decoder.layers.7.1.fn.fn.net.3.bias".

**Comment by wangqingl** [comment]
> @wangqingl Same test performance?

Sorry, there were errors in some of my configurations that caused it
