### ISSUE TITLE
Inference-issue

### ISSUE THREAD

**Issue by osamaa1111** [wgcban/ChangeFormer#85]
i was trying to run demo_LEVIR script on new images for LEVIR dataset but i got very bad results and sometimes i got black image without any segmentation

can you help me?

**Comment by wgcban** [comment]
@osamaa1111 can you please check if your setup is correct. For me it is still working. Make sure you specify the correct pre-trained model and the correct dataset.

**Comment by osamaa1111** [comment]
I'm just trying the demo file, so I don't change anything but the inputted image is 1024 x 1024. I thought this is the problem but i found that you perform the resize to 256. but what do you thing the issue is ? and what are setups you recommend to check on ?
