### ISSUE TITLE
Something for ‘update the best model’

### ISSUE THREAD

**Issue by Tom-Dongfang** [wgcban/ChangeFormer#86]
Hello, thanks for the great work.
I want to talk about the main evaluation indices of the 'best model', and I noticed that ‘F1-score with regard to the change category’ is used as the main evaluation indices in your article. Then I found 'mF1' which is the mean F1-score with regard to the change category and unchange category was used for updating for the bset model.
![1](https://github.com/wgcban/ChangeFormer/assets/44158474/dc361977-9f35-485f-811a-4320e8c67f4c)
So I want to talk about whe
Therefore, I would like to ask which indicator mF1 or F1_1( F1-score with regard to the change category) is more suitable as the basis for the output of the bset model.
Thanks again and look forward to your reply.

**Comment by wgcban** [comment]
@Tom-Dongfang your question make sense for me!

Note that, `F1_11` can be `1.0` if network predicts `1.0` as the output for all pixels. Hence, we used `mF1` to update the `best_model` so we know the `best_model` can accurately predict both `change` and `no-change` classes (not only the `change-class`).

However, you can use `F_1` as the performance indicator to update the `best model` -- which is mostly align with our objective. 

Thanks!

**Comment by Tom-Dongfang** [comment]
Thank you for your reply！
