### ISSUE TITLE
Does the "predict. py" file exist？

### ISSUE THREAD

**Issue by FENGJIANJUN99** [wgcban/ChangeFormer#87]
Hello author:
I want to batch predict a batch of images and calculate the final IoU and other parameters. Is there any Python program related to prediction in the code you provided? For example, "predict. py" can achieve the final change detection result by reading the trained weight file, inputting a test image and a standard image, which I haven't found yet

**Comment by wgcban** [comment]
Hi @FENGJIANJUN99 
Check [eval_cd.py](https://github.com/wgcban/ChangeFormer/blob/main/eval_cd.py).

**Comment by FENGJIANJUN99** [comment]
> Hi @FENGJIANJUN99 Check [eval_cd.py](https://github.com/wgcban/ChangeFormer/blob/main/eval_cd.py).

Okay, thank you very much for your reply. When I was running "eval_cd. py", the program reported the following error: "size mismatch for transformer decoder layers. 0.0. fn. fn. to_q.weight: copying a param with shape torch. Size ([512, 32]) from checkpoint, the shape in current model is torch. Size ([64, 32])." May I ask if this is because the batch size is set to 8, as I noticed that 512 is eight times 64, The vis prediction graph generated during the training phase is also output with eight graphs placed in one graph
