### ISSUE TITLE
multi-class datasets issues

### ISSUE THREAD

**Issue by wangqingl** [wgcban/ChangeFormer#88]
Hello, My dataset has ten categories of changes, and I have defined labels as numbers from 0 to 9. The modifications I made in the code are shown in the following figure. Is this feasible?
![image](https://github.com/wgcban/ChangeFormer/assets/102707449/c5f1e5ba-fa5b-47e9-84b0-8ed98bf17796)
When testing the effectiveness of the trained model, I made modifications to the tested code, as shown in the following figure. I deleted the "* 255" in the code. But the test result is a pure black single channel image, which means that the trained model has no effect. How can this be solved? Looking forward to your reply.
![image](https://github.com/wgcban/ChangeFormer/assets/102707449/c5801ea3-2107-4519-b76e-bead73b73e89)

**Comment by wgcban** [comment]
@wangqingl Did you able to manage this issue?
