### ISSUE TITLE
pretrain

### ISSUE THREAD

**Issue by xbysq** [wgcban/ChangeFormer#9]
Hello, I'm a beginner and I didn't find a pretrained model, can you help me?
pretrain=/media/lidan/ssd2/ChangeFormer/pretrained_segformer/segformer.b2.512x512.ade.160k.pth
You write this in your code, I don't have it。

**Comment by wgcban** [comment]
Hey @xbysq,
Thank you for pointing out this. 

When we train our ChangeFormer, we initialized some parameters of the network with a model pre-trained on the RGB segmentation (ADE 160k dataset) to get faster convergence. 

I forgot to update this detail in the readme file and thank you for pointing out this.

You can download the pre-trained model [here](https://www.dropbox.com/sh/4uh7y4a3r77asvo/AACHUnArhg6Cfiw5P3z-L2ACa?dl=0). 

Let me know if you need any further help.

Best,
Chaminda

**Comment by wgcban** [comment]
Hi @xbysq 
I have updated the readme file and you can find more details [here](https://github.com/wgcban/ChangeFormer/blob/main/README.md#train-on-levir-cd)

**Comment by xbysq** [comment]
> Hi @xbysq I have updated the readme file and you can find more details [here](https://github.com/wgcban/ChangeFormer/blob/main/README.md#train-on-levir-cd).

Hi@wgcban, first of all thanks for your reply. Sorry, I want to tell you a question, I can't open your link, I guess it is dropbox, maybe I can't download it, can you put it on github?
