### ISSUE TITLE
models模块

### ISSUE THREAD

**Issue by kk-kaii** [wgcban/ChangeFormer#92]
![image](https://github.com/wgcban/ChangeFormer/assets/105615283/060e4511-13b8-4e0b-ba19-544dd8d352c5)
您好 我用您的代码想一起复现FC-EF和FE-diff和FE-conc为啥跑出来F1为0啊 但是跑其他的网络比如DTCDSCN就能跑出来 什么原因啊 望回复

**Comment by wgcban** [comment]
Without much details, I am not exactly sure why the F1 is zero in your case. Check the training loss curves and see if the model is fitting properly. Maybe you are loading the data incorrectly?

**Comment by kk-kaii** [comment]
> Without much details, I am not exactly sure why the F1 is zero in your case. Check the training loss curves and see if the model is fitting properly. Maybe you are loading the data incorrectly?
I checked it once and there's no problem. I just checked -- net_ G changed to UNet and started training, but F1 was always 0, but the other few networks were fine, only the FC-EF three networks

**Comment by wgcban** [comment]
Could you pls explain your issue?
