### ISSUE TITLE
(change-detection) C:\Users\Administrator\ChangeFormer>pip install -r requirements.txt ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 16 of requirements.txt) Hint: = is not a valid operator. Did you mean == ?

### ISSUE THREAD

**Issue by ayshaashra** [wgcban/ChangeFormer#97]
When i am running the pip install -r requirements.txt command on Anaconda Prompt, I am facing errors like ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
Then I updated it with new version of requirements.txt after running the command I got the errors:
ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 16 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

**Comment by wgcban** [comment]
@ayshaashra thanks for your question. 

I think this is happening because you are installing it with pip (the provided requirement file is not compatible with pip). 

Try installing requirements.txt with conda as follows (see [setting-up-conda-environement](https://github.com/wgcban/ChangeFormer?tab=readme-ov-file#setting-up-conda-environment)):
```
conda create --name ChangeFormer --file requirements.txt
conda activate ChangeFormer
```

Thanks.

**Comment by ayshaashra** [comment]
Please guide me should I use the requirements.txt or the "Updated Requirement file". As I try with both files of requirement but do not able to solve it, I am running it on the Anacoda Prompt. Everything before is properly running but this command is not running, I have checked the relevant post also and tried it by adding == instead of = sign

**Comment by ayshaashra** [comment]
conda install --file requirements.txt
Yes this is working thank you

**Comment by wgcban** [comment]
Great!
