### ISSUE TITLE
Compatibility issues of CUDA 

### ISSUE THREAD

**Issue by ayshaashra** [wgcban/ChangeFormer#98]
With Python =8.0
 pytorch==1.10.1
 torchvision==0.11.2 
torchaudio==0.10.1
I have tried cudatoolkit=10.2, 10.1, 10.4 now trying 11.3 CUDA 
but I am facing the same error, please guide me what to do? @wgcban 
![image](https://github.com/wgcban/ChangeFormer/assets/111525482/612ff3db-c783-4127-99fe-a47e8991fc4d)

I have added environment variables also
![image](https://github.com/wgcban/ChangeFormer/assets/111525482/d06788dd-36bc-4c32-9658-fc404527feba)

**Comment by derow0208** [comment]
little advice: using linux os such as ubunto shuould work

**Comment by ayshaashra** [comment]
Ok thanks for letting me know.

**Comment by wgcban** [comment]
@ayshaashra as @derowtosky mentioned, this codebase has tested on linux and I prefer you to use linux environment.
