### ISSUE TITLE
Something about the pretrained_changeformer.pt file.

### ISSUE THREAD

**Issue by liberty-MCYE** [wgcban/ChangeFormer#99]
Dear Bandara:

Regarding the context of #96's Q&A, there are some lingering confusions about pre-trained models that I would appreciate your clarification on.

In regards to the training of Changeformer on the LEVIR dataset, you mentioned in the readme that the model was initially pre-trained on the ADE 160k dataset. However, the pretrained weights provided in your GitHub repository are the weights obtained after training specifically on the LEVIR dataset itself. The expired file at the wget link
https://www.dropbox.com/s/undtrlxiz7bkag5/pretrained_changeformer.pt 
appears to have been intended for the weights resulting from the pretraining phase on the ADE 160k dataset. If this is indeed the case, could you please provide an alternative channel or updated link to download the pre-trained weights for Changeformer on the ADE 160k dataset?

Furthermore, in the text file provided for the training process on the LEVIR dataset, it is mentioned that: 
pretrain: /media/lidan/ssd2/ChangeFormer/pretrained_segformer/segformer.b2.512x512.ade.160k.pth
Does this indicate that during training on the LEVIR dataset, the pre-trained weights from SegFormer's mit-B2 model were directly utilized? Please advise.

Thank you very much.

**Comment by wgcban** [comment]
Hi @liberty-MCYE Thanks for your question. No, we didn't utilize the segformer weights, but used model trained on DSIFN as pre-trained weights for LEVIR.

**Comment by liberty-MCYE** [comment]
Dear Bandara:

Thank you for your response. Regarding your response, I have further inquiries that I would appreciate having addressed.

1.If training LEVIR involves the use of pre-trained weights derived from a model trained on the DSIFN dataset. When initially training on the DSIFN dataset, were pre-trained weights used? 

2.Furthermore, in the readme, it is mentioned that "When we initially train our ChangeFormer, we initialize certain parameters of the network using a model pre-trained on RGB segmentation (the ADE 160k dataset) to attain faster convergence." Could you please advise on how to obtain the pre-trained weights trained on the ADE 160k dataset?

Thank you very much.

**Comment by wgcban** [comment]
@liberty-MCYE thanks for your question. Our initial experiments utilized pre-trained weights on ADE160K. However, I misplaced the pre-trained model and cannot find it now. That's why I mentioned previously to use pre-trained weights on an another dataset. This is just to make sure model converges after -- so you don't have to run all the epochs to get the results. However, it is not necessary, you can train from scratch -- in this case you need to train the model all the training epochs (120) get the results.  Thanks.
